apiVersion: skaffold/v2beta8
kind: Config

metadata:
  name: blog

deploy:
  kubectl:
    manifests:
      - ./kubernetes/*

build:
  googleCloudBuild:
    projectId: ticketshop-dev-297312

  artifacts:
    - image: confortichristian/auth
      context: auth
      docker:
        dockerfile: docker/Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .