apiVersion: skaffold/v2beta8
kind: Config

metadata:
  name: blog

deploy:
  kubectl:
    manifests:
      - ./kubernetes/*

build:
  local:
    push: false

  artifacts:
    - image: confortichristian/auth
      context: auth
      docker:
        dockerfile: docker/Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .

    - image: confortichristian/client
      context: client
      docker:
        dockerfile: docker/Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    
    - image: confortichristian/tickets
      context: tickets
      docker:
        dockerfile: docker/Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .